env: dev
port: 6666

db:
  user: postgres
  password: postgres
  host: postgres
  port: 5432
  name: fin-agg-db

cronTabs:
  checkOffersCronTab: "*/30 * * * * *"

banks:
  fastBankURL: https://shop.stage.klix.app/api/FastBank
  solidBankURL: https://shop.stage.klix.app/api/SolidBank
