version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-6666}:6666"
    environment:
      - KTT_DB_HOST=postgres
    depends_on:
      - postgres_migrate

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fin-agg-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_migrate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    environment:
      - KTT_DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - ./migrate

volumes:
  postgres_data:
