// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repositories/application.go

// Package mock_repositories is a generated GoMock package.
package mock_repositories

import (
	context "context"
	models "financing-aggregator/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockApplicationRepository is a mock of ApplicationRepository interface.
type MockApplicationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationRepositoryMockRecorder
}

// MockApplicationRepositoryMockRecorder is the mock recorder for MockApplicationRepository.
type MockApplicationRepositoryMockRecorder struct {
	mock *MockApplicationRepository
}

// NewMockApplicationRepository creates a new mock instance.
func NewMockApplicationRepository(ctrl *gomock.Controller) *MockApplicationRepository {
	mock := &MockApplicationRepository{ctrl: ctrl}
	mock.recorder = &MockApplicationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplicationRepository) EXPECT() *MockApplicationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockApplicationRepository) Create(ctx context.Context, app *models.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockApplicationRepositoryMockRecorder) Create(ctx, app interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockApplicationRepository)(nil).Create), ctx, app)
}

// GetWithProcessedOffers mocks base method.
func (m *MockApplicationRepository) GetWithProcessedOffers(ctx context.Context, id string) (models.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithProcessedOffers", ctx, id)
	ret0, _ := ret[0].(models.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithProcessedOffers indicates an expected call of GetWithProcessedOffers.
func (mr *MockApplicationRepositoryMockRecorder) GetWithProcessedOffers(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithProcessedOffers", reflect.TypeOf((*MockApplicationRepository)(nil).GetWithProcessedOffers), ctx, id)
}
